---
- name: Update and Upgrade CS-K8S
  hosts: CS-K8S
  tasks:
  - name: Update and Upgrade apt packages
    become: true
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
  - name: Drain each host, reboot, and uncordon
    throttle: 1
    block:
      - name: Drain Host
        become: true
        become_method: sudo su -
        ansible.builtin.shell: kubectl drain $(hostname|tr '[:upper:]' '[:lower:]') --ignore-daemonsets
      - name: Reboot Host
        become: true
        ansible.builtin.reboot:
          reboot_timeout: 3600
      - name: Wait for Connection
        wait_for_connection:
          connect_timeout: 10
          sleep: 5
          delay: 5
          timeout: 300
      - name: Uncordon Host
        become: true
        ansible.builtin.shell: kubectl uncordon $(hostname|tr '[:upper:]' '[:lower:]')