---
- name: Update and Upgrade CS-K8S
  hosts: CS-K8S
  become: true
  tasks:
  - name: Update apt packages
    ansible.builtin.apt:
      update_cache: yes
  - name: Upgrade apt packages
    ansible.builtin.apt:
      upgrade: yes