- name: Get hostnames
  hosts: CS-K8S
  serial: 1
  tasks:
    - name: Collect Hostname
      ansible.builtin.shell: "hostname|tr '[:upper:]' '[:lower:]'"
      register: hostname
    - name: Print hostname
      ansible.builtin.debug:
        msg: "{{ hostname.stdout }}"


