# vars:
#   hostnames

- name: Get hostnames
  hosts: CS-K8S
  tasks:
    - name: Add Hostname
      ansible.builtin.debug:
        hostnames: "{{ hostnames + ansible_hostname }}"

- name: Print Hostnames
  tasks:
    - name: Print Hostnames
      ansible.builtin.debug:
        msg: "{{ hostnames }}"