- name: Get hostnames
  hosts: CS-K8S
  serial: 1
  tasks:
    - name: Add Hostname
      ansible.builtin.shell: "hostname|tr '[:upper:]' '[:lower:]'"
      register: hostnames
    - name: Print Hostnames
      ansible.builtin.debug:
        msg: "{{ hostnames.stdout }}"